version: '2'

services:
  postgres:
    image: shintech/database
    container_name: postgres
    env_file:
      - ./db.env    
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    restart: always
#     networks:
#       default:
#         ipv4_address: 192.168.0.8
# networks:
#   default:
#     external:
#       name: shintech  